/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "xix_event.h"

extern const oid snmptrap_oid[];
extern const size_t snmptrap_oid_len;

int
send_xixEventSet_trap(char *xixEventId, char *xixEventText)
{
    netsnmp_variable_list  *var_list = NULL;
    const oid xixEventSet_oid[] = { 1,3,6,1,4,1,32979,1,1,0,1 };
    const oid xixEventId_oid[] = { 1,3,6,1,4,1,32979,1,1,1,1, 0 };
    const oid xixEventText_oid[] = { 1,3,6,1,4,1,32979,1,1,1,2, 0 };

    /*
     * Set the snmpTrapOid.0 value
     */
    snmp_varlist_add_variable(&var_list,
        snmptrap_oid, snmptrap_oid_len,
        ASN_OBJECT_ID,
        xixEventSet_oid, sizeof(xixEventSet_oid));
    
    /*
     * Add any objects from the trap definition
     */
    snmp_varlist_add_variable(&var_list,
        xixEventId_oid, OID_LENGTH(xixEventId_oid),
        ASN_OCTET_STR,
        xixEventId,
        strlen(xixEventId));

    snmp_varlist_add_variable(&var_list,
        xixEventText_oid, OID_LENGTH(xixEventText_oid),
        ASN_OCTET_STR,
        xixEventText,
        strlen(xixEventText));

    /*
     * Send the trap to the list of configured destinations
     *  and clean up
     */
    send_v2trap( var_list );
    snmp_free_varbind( var_list );

    return SNMP_ERR_NOERROR;
}
int
send_xixEventClear_trap(char *xixEventId)
{
    netsnmp_variable_list  *var_list = NULL;
    const oid xixEventClear_oid[] = { 1,3,6,1,4,1,32979,1,1,0,2 };
    const oid xixEventId_oid[] = { 1,3,6,1,4,1,32979,1,1,1,1, 0 };

    /*
     * Set the snmpTrapOid.0 value
     */
    snmp_varlist_add_variable(&var_list,
        snmptrap_oid, snmptrap_oid_len,
        ASN_OBJECT_ID,
        xixEventClear_oid, sizeof(xixEventClear_oid));
    
    /*
     * Add any objects from the trap definition
     */
    snmp_varlist_add_variable(&var_list,
        xixEventId_oid, OID_LENGTH(xixEventId_oid),
        ASN_OCTET_STR,
        xixEventId,
        strlen(xixEventId));

    /*
     * Send the trap to the list of configured destinations
     *  and clean up
     */
    send_v2trap( var_list );
    snmp_free_varbind( var_list );

    return SNMP_ERR_NOERROR;
}
