/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef XIX_EVENT_H
#define XIX_EVENT_H

/* function declarations */
int send_xixEventSet_trap(char *xixEventId, char *xixEventText);
int send_xixEventClear_trap(char *xixEventId);

#endif /* XIX_EVENT_H */
